Friendship v2 final version
karthi07/social-media-app pull request #3
Opened 2020-05-26 09:01 UTC by jaspreet-singh-sahota

- Added mutual friendship for both users after confirming an invite from the other user
- Added integration testing for friendship controller

2020-05-26 13:23 UTC, mosaaleb requested changes
#### Excellent work @jaspreet-singh-sahota @karthi07 :clap:

Most requirements are handled, still, we have to work on some minor requirements before moving on:

Please take a look at my comments below

##### Muhammad Ebeid

2020-05-26 13:23 UTC, mosaaleb commented on app/models/user.rb
> +    confrimation = inverse_invitations.find { |invite| invite.user == user }
- [x] when friendship is confirmed, an additional row with reversed user-friend pair is created -- Let's add here invitation duplication logic,

Thanks to this we are no longer have to go through `inverse_invitations` to find a user friends

2020-05-26 13:23 UTC, mosaaleb commented on app/models/user.rb
> +
- [x] User#pending_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

We can use [`has_many :through`](https://guides.rubyonrails.org/association_basics.html#the-has-many-through-association) to achieve this:

```ruby
has_many :pending_invitations, -> { where is_accepted: false }, class_name: "Invitation", foreign_key: "user_id"
has_many :pending_friends, through: :pending_invitations, source: :friend

# or we can combine these two quries in a sinle query
has_many :pending_friends, -> { where(invitations: { is_accepted: false }) }, through: :invitations, source: :friend
```

2020-05-26 13:23 UTC, mosaaleb commented on app/models/user.rb
> +
- [ ] Same for finding friends who requested a friendship:

```ruby
has_many :inverse_pending_invitations, -> { where is_accepted: false }, class_name: "Invitation", foreign_key: "friend_id"
has_many :inverse_pending_friends, through: :inverse_pending_invitations
```

2020-05-26 13:23 UTC, mosaaleb commented on app/controllers/posts_controller.rb
> +    @timeline_posts = Post.where(user: current_user.friends).or(Post.where(user: current_user)).ordered_by_most_recent
- [ ] where clause can take an array, so we could re-write this as:
```ruby
Post.where(user: current_user.friends + [current_user.id])
```
I also suggest that you move this logic as a method in user model:

```ruby
def timeline_posts
  Post.where(user: friends + [id])
end
```
to make it reusable.

2020-05-26 13:23 UTC, mosaaleb commented on app/models/user.rb
> +  def friends
- [ ] Same concept for `friends` let's re-write in using `has_many :through`

2020-05-26 13:23 UTC, mosaaleb commented on spec/features/friend_request_spec.rb
> +  user1 = ['user1', 'user1@test.com', 'password1']
- **[OPTIONAL]** We can clean this setup using `factory_bot` gem, which gives you ability to generate fast test objects.

2020-05-26 13:23 UTC, mosaaleb commented on spec/models/users_spec.rb
> +    it { should have_many(:invitations) }
- [ ] There are some association and instance methods in user model that are not tested yet -- Let's add them

Also if you have decided to move the `timeline_posts` method in user model don't forget to add its tests.

2020-05-27 12:18 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi there team :hand: 
Great job implementing most of the required changes :+1: :clap: 
But there are still some changes we need to make before moving on.

- [x] As it was pointed out in the previous review, there are some associations and instance methods in user model that are not tested yet. I also noticed that there are no feature tests for creating posts, comments, or liking a post.

- [x] I was able to see a post from another user in my timeline before the friendship was confirmed. As requested in the guidelines, this should be only possible after the friendship requested be accepted.
[Print](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) of the requirement. 

- [ ] there is an excessive number of files in your project, more than 8000. This is making github page run very slow in the files-changed page. I think this is due to the fact that the bundle folder was pushed to the repo. I know that you added to your .gitignore file but it is inside the vendor directory. 

Kindly submit for code review again after making these changes.
Feel free to message me on slack with you have any questions.

Happy coding :computer: 
**Sergio Torres**

2020-05-27 18:35 UTC, nikasulo reviewed
# Great job team! 
Please merge and keep moving forward! I wish you the very best and see you at the top :+1: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-05-27 19:37 UTC, merged